// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOJegHLXa0NwahUXnucoy_-FUll_bPwXY',
    appId: '1:249451013181:web:b144459c3ab58b70cdb654',
    messagingSenderId: '249451013181',
    projectId: 'real-estate-d6171',
    authDomain: 'real-estate-d6171.firebaseapp.com',
    storageBucket: 'real-estate-d6171.appspot.com',
    measurementId: 'G-DYHB4LB9C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VTGAeqysiL5FYo5qto4fUPLCLJveCfA',
    appId: '1:249451013181:android:77ecfc52204f113ccdb654',
    messagingSenderId: '249451013181',
    projectId: 'real-estate-d6171',
    storageBucket: 'real-estate-d6171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0eVF3_tlIo5iBDk2ZYNWZzEe-2ZcWxCw',
    appId: '1:249451013181:ios:015c130dfed8e73bcdb654',
    messagingSenderId: '249451013181',
    projectId: 'real-estate-d6171',
    storageBucket: 'real-estate-d6171.appspot.com',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0eVF3_tlIo5iBDk2ZYNWZzEe-2ZcWxCw',
    appId: '1:249451013181:ios:015c130dfed8e73bcdb654',
    messagingSenderId: '249451013181',
    projectId: 'real-estate-d6171',
    storageBucket: 'real-estate-d6171.appspot.com',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOJegHLXa0NwahUXnucoy_-FUll_bPwXY',
    appId: '1:249451013181:web:55cb8ed02d107e8acdb654',
    messagingSenderId: '249451013181',
    projectId: 'real-estate-d6171',
    authDomain: 'real-estate-d6171.firebaseapp.com',
    storageBucket: 'real-estate-d6171.appspot.com',
    measurementId: 'G-MW8TVZ6CSN',
  );
}
